### ISSUE TITLE
Sponsor List - Logo Sizes

### ISSUE THREAD

**Issue by oliviasauls** [psf/pycon-us-mobile#64]
In the Sponsor List, the sponsor logos are all in various sizes - some bigger and some smaller (example - Microsoft)

Can we make these uniform? 

![img_6039_720_720](https://github.com/psf/pycon-us-mobile/assets/89146495/070549e6-a091-4703-b3c2-6a099d510051)

**Comment by ewdurbin** [comment]
The resulting sponsor logo sizes are a result of the files submitted by sponsors you can see similar inconsistencies on https://us.pycon.org/2024/sponsorship/sponsors/

In order to standardize sizes we would need either edit the submitted logos or request updates from the sponsors.

In this case, capital one appears larger since they did not submit a logo with any margin, the artwork is edge to edge:

<img width="660" alt="Screenshot 2024-02-20 at 12 25 59 PM" src="https://github.com/psf/pycon-us-mobile/assets/1200832/50625845-3172-4163-b41a-e7bcd9591415">

whereas microsoft submitted one with "padding":

<img width="676" alt="Screenshot 2024-02-20 at 12 25 48 PM" src="https://github.com/psf/pycon-us-mobile/assets/1200832/5b4ce877-9b9a-4556-bb21-03168f7e885c">

I don't consider this an issue with us.pycon.org or the mobile site.
